# Generated by Django 5.2.16 on 2026-08-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_options_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="blog/defult.jpg", upload_to="blog/"),
        ),
    ]
